# Generated by Django 3.1.3 on 2020-11-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='base_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.size'),
        ),
    ]
