# Generated by Django 3.1.3 on 2020-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_auto_20201123_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='test', max_length=24),
            preserve_default=False,
        ),
    ]
