# Generated by Django 3.1.3 on 2020-11-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pizzeria", "0005_auto_20201123_1948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="topping",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="topping",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toppings",
                to="pizzeria.topping",
            ),
            preserve_default=False,
        ),
    ]
