# Generated by Django 3.1.3 on 2020-11-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_auto_20201123_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizzeria.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.topping'),
        ),
    ]
