# Generated by Django 3.1.3 on 2020-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_auto_20201124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
