# Generated by Django 3.1.3 on 2020-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0011_auto_20201127_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_dispatched',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_made',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('dispatched', 'dispatched'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
